AWSTemplateFormatVersion: '2010-09-09'
Description: 'Terraform Backend Resources: S3 Bucket for State and DynamoDB for Locking'

Parameters:
  ProjectName:
    Type: String
    Default: 'basic-iac-pipeline'
    Description: 'A name to prefix resources'

Resources:
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-terraform-state-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  TerraformLockTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${ProjectName}-terraform-locks'
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  StateBucketName:
    Value: !Ref TerraformStateBucket
  DynamoDBTableName:
    Value: !Ref TerraformLockTable
