name: "Terraform IaC Pipeline"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write # Required for AWS OIDC authentication
  contents: write # Required for yor-action to push tagging changes

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.TF_BACKEND_REGION }}
          # Requires these secrets to be set in GitHub:
          # AWS_ACCESS_KEY_ID: <Your Access Key>
          # AWS_SECRET_ACCESS_KEY: <Your Secret Key>
          # For production, use OIDC role-to-assume for better security
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply yor tags
        uses: bridgecrewio/yor-action@main

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}" -backend-config="region=${{ secrets.TF_BACKEND_REGION }}" -backend-config="key=state/terraform.tfstate"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
